# Generated by Django 5.0.6 on 2024-06-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='eTime',
            field=models.TimeField(verbose_name='활성화종료시간'),
        ),
        migrations.AlterField(
            model_name='place',
            name='sTime',
            field=models.TimeField(verbose_name='활성화시작시간'),
        ),
    ]
