# Generated by Django 5.0.6 on 2024-06-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_place_etime_alter_place_stime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('work_time', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='place_image', verbose_name='이미지1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='place_image', verbose_name='이미지2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='place_image', verbose_name='이미지3')),
            ],
        ),
    ]
